service: notes-crud-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  profile: perpion-sanka
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  # apiGateway:
  #   apiKeys:
  #     - name: api-key-${self:provider.stage}
  #       value: super-secret-api-key-${self:provider.stage}
  #   usagePlan:
  #     quota:
  #       limit: 100
  #       offset: 0
  #       period: DAY
  #     throttle:
  #       burstLimit: 10
  #       rateLimit: 100
  environment:
    NOTES_TABLE_NAME: !Ref notesTable

plugins:
  - serverless-iam-roles-per-function

functions:
  authorizer: # lambda authorizer function
    handler: authorizer.handler
    environment:
      COGNITO_USER_POOL_ID: !Ref cognitoUserPool
      COGNITO_WEB_CLIENT_ID: !Ref cognitoUserPoolWebClient

  createNote:
    handler: handler.createNote
    events:
      - http:
          method: post
          path: notes
          authorizer: authorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt notesTable.Arn

  updateNote:
    handler: handler.updateNote
    events:
      - http:
          method: put
          path: notes/{id}
          authorizer: authorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt notesTable.Arn

  deleteNote:
    handler: handler.deleteNote
    events:
      - http:
          method: delete
          path: notes/{id}
          authorizer: authorizer
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt notesTable.Arn

  getNoteById:
    handler: handler.getNoteById
    events:
      - http:
          method: get
          path: notes/{id}
          authorizer: authorizer
    iamRoleStatements:
      - Effect: "Allow"
        Resource: !GetAtt notesTable.Arn
        Action: "dynamodb:GetItem"

  getAllNotes:
    handler: handler.getAllNotes
    events:
      - http:
          method: get
          path: notes/
          #private: true
          authorizer:
            name: userpool_authorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt cognitoUserPool.Arn # Using the logical name of the resource
    iamRoleStatements:
      - Effect: "Allow"
        Resource: !GetAtt notesTable.Arn
        Action: "dynamodb:Scan"

# CloudFormation resources
resources:
  Resources: ${file(resources.yml)}
